#page title
page_title                                : Vibur - Unpleasant and pleasant events calendar

# App Info
ios_app_id                                : 1592169625
ios_app_country                           : us

appstore_link                             : https://apps.apple.com/us/app/vibur/id1592169625
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png
app_name                                  : Vibur
app_price                                 : 
app_description                           : Unpleasant and pleasant events calendar
enable_smart_app_banner                   : true

# Information About Yourself
your_name                                 : Kristaps Grinbergs                               
your_link                                 : https://kristaps.me
your_city                                 : Latvia 🇱🇻                      
email_address                             : kristaps@hey.com
facebook_username                         :                                           
instagram_username                        : ios_nomad
twitter_username                          : fassko
github_username                           : fassko
youtube_username                          :


# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Events
    description                           : Unpleasant and pleasant events calendar.
    fontawesome_icon_name                 : calendar
    
  - title                                 : Export
    description                           : Export the full list of your recorded events.
    fontawesome_icon_name                 : cloud-download-alt

  - title                                 : Reminders
    description                           : Set up reminders to record an event.
    fontawesome_icon_name                 : bell

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.7
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
